# Generated by Django 3.2.7 on 2022-01-06 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0002_dialog_creation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialogmessage',
            options={'ordering': ['sending_date'], 'verbose_name': 'Сообщения', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterField(
            model_name='dialogmessage',
            name='dialog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dialogs.dialog'),
        ),
    ]
