# Generated by Django 3.2.7 on 2022-01-30 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0005_auto_20220122_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unreadmessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unread_messages', to='dialogs.dialogmessage'),
        ),
    ]
