# Generated by Django 3.2.7 on 2022-06-03 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dialogs', '0006_alter_unreadmessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_dialogs', to=settings.AUTH_USER_MODEL, verbose_name='Создатель диалога'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responding_dialogs', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='dialogmessage',
            name='content',
            field=models.TextField(max_length=150, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='dialogmessage',
            name='dialog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dialogs.dialog', verbose_name='Диалог'),
        ),
        migrations.AlterField(
            model_name='dialogmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='dialogmessage',
            name='sending_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки'),
        ),
    ]
