# Generated by Django 3.2.7 on 2021-12-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Женский'), ('Female', 'Мужской'), ('Not specified', 'Не указан')], default='Not specified', max_length=15, verbose_name='Пол'),
        ),
    ]
