# Generated by Django 3.2.7 on 2021-12-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_birthday_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about_user',
            field=models.TextField(blank=True, null=True, verbose_name='Коротко о себе'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pc_configuration',
            field=models.TextField(blank=True, null=True, verbose_name='Кофнигурация компьютера'),
        ),
    ]
