# Generated by Django 3.2.7 on 2021-12-22 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_about_user_customuser_about_custom_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='pc_configuration',
        ),
    ]
