# Generated by Django 3.2.7 on 2021-12-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(default='defaultUserProfile.png', upload_to='', verbose_name='Изображение профиля'),
        ),
    ]
