# Generated by Django 3.2.7 on 2021-12-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_customuser_pc_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский'), ('Не указан', 'Не указан')], default='Не указан', max_length=15, verbose_name='Пол'),
        ),
    ]
