# Generated by Django 3.2.7 on 2021-12-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение профиля'),
        ),
    ]
