# Generated by Django 3.2.7 on 2022-03-01 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUserRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.TextField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default=None)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.CreateModel(
            name='RateUser',
            fields=[
                ('useruserrelation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.useruserrelation')),
            ],
            bases=('users.useruserrelation',),
        ),
        migrations.AddField(
            model_name='useruserrelation',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useruserrelation',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
