# Generated by Django 3.2.7 on 2022-03-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220301_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruserrelation',
            name='rate',
            field=models.TextField(blank=True, choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default=None, null=True),
        ),
        migrations.DeleteModel(
            name='RateUser',
        ),
    ]
