# Generated by Django 3.2.7 on 2022-05-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20220411_1656'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='news', to='games.Game', verbose_name='Игра'),
        ),
    ]
