# Generated by Django 3.2.7 on 2021-09-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='category',
        ),
        migrations.AddField(
            model_name='newsitem',
            name='categories',
            field=models.ManyToManyField(to='news.NewsCategory', verbose_name='Категории'),
        ),
    ]
