# Generated by Django 3.2.7 on 2022-06-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsitem_games'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsitem',
            old_name='image',
            new_name='img',
        ),
    ]
