# Generated by Django 3.2.7 on 2022-01-01 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20220101_1426'),
        ('news', '0002_alter_newsitem_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.game', verbose_name='Игра'),
        ),
    ]
