# Generated by Django 3.2.7 on 2022-01-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20220101_1426'),
        ('news', '0004_alter_newsitem_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='game',
        ),
        migrations.AddField(
            model_name='newsitem',
            name='game',
            field=models.ManyToManyField(blank=True, null=True, to='games.Game', verbose_name='Игра'),
        ),
    ]
