# Generated by Django 3.2.7 on 2022-01-01 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20220101_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsitem',
            old_name='game',
            new_name='games',
        ),
    ]
