# Generated by Django 3.2.7 on 2022-01-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20220101_1426'),
        ('news', '0006_rename_game_newsitem_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='games',
            field=models.ManyToManyField(blank=True, to='games.Game', verbose_name='Игра'),
        ),
    ]
