# Generated by Django 3.2.7 on 2022-01-31 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('content', models.TextField(verbose_name='Контент')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.newscomment')),
            ],
        ),
        migrations.CreateModel(
            name='NewsCommentComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Контент для взрослых', 'Контент для взрослых'), ('Мультиаккаунт', 'Мультиаккаунт'), ('Оскорбление', 'Оскорбление'), ('Реклама', 'Реклама'), ('Спам', 'Спам'), ('Другое', 'Другое')], max_length=20, verbose_name='Причина')),
                ('time_add', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки жалобы.')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.newscomment', verbose_name='Комментарий')),
            ],
        ),
    ]
