# Generated by Django 3.2.7 on 2022-04-03 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('content', models.TextField(verbose_name='Контент')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален ли')),
                ('rating', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.newsitem', verbose_name='Новость')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comments.newscomment')),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='UserCommentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.TextField(blank=True, choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default=None, null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.newscomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsCommentComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Контент для взрослых', 'Контент для взрослых'), ('Мультиаккаунт', 'Мультиаккаунт'), ('Оскорбление', 'Оскорбление'), ('Реклама', 'Реклама'), ('Спам', 'Спам'), ('Другое', 'Другое')], max_length=20, verbose_name='Причина')),
                ('time_add', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки жалобы.')),
                ('description', models.TextField(blank=True, max_length=70, null=True, verbose_name='Описание жалобы')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.newscomment', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Жалобу',
                'verbose_name_plural': 'Жалобы',
            },
        ),
    ]
