# Generated by Django 3.2.7 on 2022-02-01 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_newsitem_games'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscomment',
            options={'ordering': ['creation_date']},
        ),
        migrations.AlterModelOptions(
            name='newscommentcomplaint',
            options={'verbose_name': 'Жалобу', 'verbose_name_plural': 'Жалобы'},
        ),
        migrations.AddField(
            model_name='newscomment',
            name='news_item',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='news.newsitem', verbose_name='Новость'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comments.newscomment'),
        ),
    ]
