# Generated by Django 3.2.7 on 2022-05-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscomment',
            name='content',
            field=models.TextField(max_length=100, verbose_name='Контент'),
        ),
    ]
