# Generated by Django 3.2.7 on 2022-05-22 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_alter_newsitem_games'),
        ('blogs', '0011_alter_bloguserrelation_rate'),
        ('comments', '0002_alter_newscomment_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('content', models.TextField(max_length=100, verbose_name='Контент')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален ли')),
                ('rating', models.IntegerField(default=0)),
                ('blog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to='blogs.blog', verbose_name='Блог')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comments.blogcomment')),
            ],
            options={
                'verbose_name': 'Комментарий блога',
                'verbose_name_plural': 'Комментарии блогов',
                'ordering': ['creation_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogCommentComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Контент для взрослых', 'Контент для взрослых'), ('Мультиаккаунт', 'Мультиаккаунт'), ('Оскорбление', 'Оскорбление'), ('Реклама', 'Реклама'), ('Спам', 'Спам'), ('Другое', 'Другое')], max_length=20, verbose_name='Причина')),
                ('time_add', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки жалобы.')),
                ('description', models.TextField(blank=True, max_length=70, null=True, verbose_name='Описание жалобы')),
                ('blog_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.blogcomment', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Жалобу',
                'verbose_name_plural': 'Жалобы',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserBlogCommentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.blogcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserNewsCommentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='newscomment',
            options={'ordering': ['creation_date'], 'verbose_name': 'Комментарий новости', 'verbose_name_plural': 'Комментарии новостей'},
        ),
        migrations.RenameField(
            model_name='newscommentcomplaint',
            old_name='comment',
            new_name='news_comment',
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='news_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_comments', to='news.newsitem', verbose_name='Новость'),
        ),
        migrations.DeleteModel(
            name='UserCommentRelation',
        ),
        migrations.AddField(
            model_name='usernewscommentrelation',
            name='news_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.newscomment'),
        ),
        migrations.AddField(
            model_name='usernewscommentrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
