# Generated by Django 3.2.7 on 2022-02-18 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_newsitem_games'),
        ('comments', '0002_auto_20220201_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscomment',
            name='news_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.newsitem', verbose_name='Новость'),
        ),
    ]
