# Generated by Django 3.2.7 on 2022-05-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20220522_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblogcommentrelation',
            name='rate',
            field=models.TextField(blank=True, choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='usernewscommentrelation',
            name='rate',
            field=models.TextField(blank=True, choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default=None, null=True),
        ),
    ]
