# Generated by Django 3.2.7 on 2022-02-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_newscomment_news_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscomment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален ли'),
        ),
    ]
