# Generated by Django 3.2.7 on 2022-05-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20220523_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userblogcommentrelation',
            old_name='blog_comment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='usernewscommentrelation',
            old_name='news_comment',
            new_name='comment',
        ),
    ]
