# Generated by Django 3.2.7 on 2022-02-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_newscomment_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscommentcomplaint',
            name='description',
            field=models.TextField(blank=True, max_length=70, null=True, verbose_name='Описание жалоыб'),
        ),
    ]
