# Generated by Django 3.2.7 on 2022-03-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_newscommentcomplaint_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscommentcomplaint',
            name='description',
            field=models.TextField(blank=True, max_length=70, null=True, verbose_name='Описание жалобы'),
        ),
    ]
