# Generated by Django 3.2.7 on 2022-05-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20220523_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcommentcomplaint',
            old_name='blog_comment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='newscommentcomplaint',
            old_name='news_comment',
            new_name='comment',
        ),
    ]
