# Generated by Django 3.2.7 on 2022-06-03 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20220523_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcommentcomplaint',
            options={'verbose_name': 'Жалобу', 'verbose_name_plural': 'Жалобы на комментарии к блогам'},
        ),
        migrations.AlterModelOptions(
            name='newscommentcomplaint',
            options={'verbose_name': 'Жалобу', 'verbose_name_plural': 'Жалобы на комментарии к новостям'},
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comments.blogcomment', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comments.newscomment', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
