# Generated by Django 3.2.7 on 2022-05-02 15:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('content', models.TextField(verbose_name='Контент')),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
    ]
