# Generated by Django 3.2.7 on 2022-05-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_contentimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentimage',
            old_name='img',
            new_name='image',
        ),
    ]
