# Generated by Django 3.2.7 on 2022-05-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_rename_img_contentimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.JSONField(verbose_name='Контент'),
        ),
    ]
