# Generated by Django 3.2.7 on 2022-05-19 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20220519_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
    ]
