# Generated by Django 3.2.7 on 2022-05-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_rename_game_bloguserrelation_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguserrelation',
            name='rate',
            field=models.TextField(blank=True, choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default=None, null=True),
        ),
    ]
