# Generated by Django 3.2.7 on 2021-10-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('platform', models.CharField(max_length=30, verbose_name='Платформа')),
                ('genre', models.CharField(max_length=30, verbose_name='Жанр')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('score', models.FloatField(max_length=10, verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
    ]
