# Generated by Django 3.2.7 on 2022-04-10 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20220410_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergamerelation',
            name='is_like',
        ),
        migrations.AddField(
            model_name='usergamerelation',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
