# Generated by Django 3.2.7 on 2021-10-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20211027_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='img',
            field=models.ImageField(default=1, upload_to='', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата выхода'),
        ),
        migrations.AlterField(
            model_name='game',
            name='score',
            field=models.FloatField(default=0, verbose_name='Оценка'),
        ),
    ]
