# Generated by Django 3.2.7 on 2022-04-10 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20220410_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergamerelation',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
