# Generated by Django 3.2.7 on 2021-11-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20211107_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-id'], 'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.RenameField(
            model_name='game',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='platform',
            new_name='platforms',
        ),
    ]
