# Generated by Django 3.2.7 on 2021-11-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20211110_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=20, unique=True, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='title',
            field=models.CharField(max_length=20, unique=True, verbose_name='Платформа'),
        ),
    ]
