# Generated by Django 3.2.7 on 2022-04-11 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_gameimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameimage',
            options={'verbose_name': 'Скриншот', 'verbose_name_plural': 'Скриншоты игры'},
        ),
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.CharField(default='None', max_length=35, verbose_name='Разработчик'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='games.game'),
        ),
    ]
